=== jantoniucci/poc-microservices-local/definitions/accounts-api/schemas/transfer.schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "id": "http://jsonschema.net",
  "required": true,
  "properties": {
    "accountIdFrom": {
      "type": "string"
    },
    "accountIdTo": {
      "type": "string"
    },
    "amount": {
      "$ref" : "amount"
    },
    "description": {
      "type": "string"
    },
    "status": {
        "type": "string",
        "enum" : [
            "sign-pending",
            "execution-pending",
            "cancelled",
            "executed"
        ]
    },
    "signers": {
       "type": "array",
       "items": { "$ref": "signer" }
    }
  }
}

=== jantoniucci/poc-microservices-local/definitions/accounts-api/samples/transfer.json
{
  "accountIdFrom" : "550e8400-e29b-41d4-a716-446655440000",
  "accountIdTo": "550e8400-e29b-41d4-a716-446655440111",
  "amount" : {
    "amount": 150.00,
    "currency": "EUR"
  },

  "description" : "example transfer",
  "status" : "sign-pending",
  "signers": [
    {
      "signerId": "11111-00000",
      "signType": "incumbent"
    }
  ]
}
